### ISSUE TITLE
REST API needs CORS header for frontend to access data

### ISSUE THREAD

**Issue by angushtlam** [ubacm/chicken#2]
https://stackoverflow.com/questions/25310450/cross-origin-resource-sharing-cors-concept

The JSON responses provided to the frontend currently do not allow 3rd party websites to pull data and use it on the frontend. The `Access-Control-Allow-Origin` header for all of these JSON responses need to be changed.

**Comment by liamgens** [comment]
Uhhhh done. Added flask_cors to do the job for me.
